// Typed wrapper around the Go WASM crypto module (cmd/wasm/main.go).
//
// Call getCrypto() once to load and instantiate the WASM binary. The returned
// service object wraps all vc* globals registered by the Go runtime. Functions
// are synchronous calls into the WASM module; Argon2id derivation blocks the JS
// thread for 1–3 seconds — show a loading spinner before calling deriveMasterKey
// or deriveAuthHash. In production, move these calls to a Web Worker.
//
// All byte arrays cross the JS/WASM boundary as standard-padded Base64 strings.

export interface KDFParams {
  type: string;
  version: number;
  memory_kib: number;
  iterations: number;
  parallelism: number;
}

export interface PlainItem {
  name: string;
  username: string;
  password: string;
  url: string;
  notes: string;
  totp_seed: string;
}

export interface StretchedKeys {
  encKey: string;
  macKey: string;
}

// Globals registered by the Go WASM runtime.
declare function vcDeriveMasterKey(password: string, email: string, kdfParamsJSON: string): string;
declare function vcDeriveAuthHash(masterKeyB64: string, password: string, kdfParamsJSON: string): string;
declare function vcStretchMasterKey(masterKeyB64: string): StretchedKeys;
declare function vcNewVaultKey(): string;
declare function vcWrapVaultKey(vaultKeyB64: string, encKeyB64: string): string;
declare function vcUnwrapVaultKey(wrappedB64: string, encKeyB64: string): string;
declare function vcSealItem(itemJSON: string, vaultKeyB64: string): string;
declare function vcOpenItem(ciphertextB64: string, vaultKeyB64: string): string;
declare function vcGeneratePassword(
  length: number,
  uppercase: boolean,
  lowercase: boolean,
  digits: boolean,
  symbols: boolean
): string;

export interface CryptoService {
  deriveMasterKey(password: string, email: string, kdfParams: KDFParams): string;
  deriveAuthHash(masterKeyB64: string, password: string, kdfParams: KDFParams): string;
  stretchMasterKey(masterKeyB64: string): StretchedKeys;
  newVaultKey(): string;
  wrapVaultKey(vaultKeyB64: string, encKeyB64: string): string;
  unwrapVaultKey(wrappedB64: string, encKeyB64: string): string;
  sealItem(item: PlainItem, vaultKeyB64: string): string;
  openItem(ciphertextB64: string, vaultKeyB64: string): PlainItem;
  generatePassword(length: number, uppercase: boolean, lowercase: boolean, digits: boolean, symbols: boolean): string;
}

// Default Argon2id parameters matching server-side DefaultKDFParams().
export const DEFAULT_KDF_PARAMS: KDFParams = {
  type: "argon2id",
  version: 19,
  memory_kib: 65536,
  iterations: 3,
  parallelism: 1,
};

let _instance: CryptoService | null = null;
let _loading: Promise<CryptoService> | null = null;

async function loadCrypto(): Promise<CryptoService> {
  if (typeof (globalThis as Record<string, unknown>).Go !== "function") {
    throw new Error(
      "Go WASM runtime not loaded. Add <script src=\"/wasm_exec.js\"></script> to index.html."
    );
  }

  // Fetch the SRI hash if available (generated by `make wasm`).
  let integrity: string | undefined;
  try {
    const sriResp = await fetch("/crypto.wasm.sri");
    if (sriResp.ok) {
      integrity = (await sriResp.text()).trim();
    }
  } catch {
    // SRI file absent — development mode without `make wasm`
  }

  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  const go = new (globalThis as any).Go();
  const wasmStream = integrity
    ? fetch("/crypto.wasm", { integrity })
    : fetch("/crypto.wasm");

  const { instance } = await WebAssembly.instantiateStreaming(wasmStream, go.importObject);
  go.run(instance); // never awaited — Go main() blocks on select{}

  // Yield one microtask so the Go runtime finishes registering globals.
  await Promise.resolve();

  if (typeof vcDeriveMasterKey !== "function") {
    throw new Error("WASM crypto functions not registered — check the build.");
  }

  const service: CryptoService = {
    deriveMasterKey: (password, email, kdfParams) =>
      vcDeriveMasterKey(password, email, JSON.stringify(kdfParams)),

    deriveAuthHash: (masterKeyB64, password, kdfParams) =>
      vcDeriveAuthHash(masterKeyB64, password, JSON.stringify(kdfParams)),

    stretchMasterKey: (masterKeyB64) => vcStretchMasterKey(masterKeyB64),

    newVaultKey: () => vcNewVaultKey(),

    wrapVaultKey: (vaultKeyB64, encKeyB64) => vcWrapVaultKey(vaultKeyB64, encKeyB64),

    unwrapVaultKey: (wrappedB64, encKeyB64) => vcUnwrapVaultKey(wrappedB64, encKeyB64),

    sealItem: (item, vaultKeyB64) => vcSealItem(JSON.stringify(item), vaultKeyB64),

    openItem: (ciphertextB64, vaultKeyB64) => {
      const json = vcOpenItem(ciphertextB64, vaultKeyB64);
      return JSON.parse(json) as PlainItem;
    },

    generatePassword: (length, uppercase, lowercase, digits, symbols) =>
      vcGeneratePassword(length, uppercase, lowercase, digits, symbols),
  };

  return service;
}

export async function getCrypto(): Promise<CryptoService> {
  if (_instance) return _instance;
  if (_loading) return _loading;
  _loading = loadCrypto().then((svc) => {
    _instance = svc;
    return svc;
  });
  return _loading;
}
